// 接入QQ 后台页的字（施工 O-28 上，docs/blueprint/onebot.md 第一条「后台页」第 4 条）：框里连不了网，读不到桥的 human/*.json，
// 三种语言放在这里，照 context 的 language 挑（app.js）。说法 O-28 上从桥自己的网页的 web/ 那几句搬来，那几句 O-28 下删了，字只在这里；ja 照英文写（同桥的规矩）。
// 字段写 {名字}。
//
// 写法要守（「施工时定的」第 159 条）：`export const TEXTS = ` 后面到最后的 `;` 是一段 JSON：不写注释、不写结尾的逗号，键用双引号。
// 测试（crates/miyu-onebot/tests/page.rs）照它读，比三种语言的键。
export const TEXTS = {
  "zh": {
    "cancel": "取消",
    "copied": "已复制",
    "copy": "复制",
    "failed": "没成：{reason}",
    "fill/address": "反向 WebSocket 地址",
    "fill/array": "数组",
    "fill/format": "消息格式",
    "fill/title": "NapCat 那边要填的",
    "fill/token": "访问令牌",
    "fill/url": "ws://127.0.0.1:{port}{path}",
    "guide/napcat": "在 NapCat 的网络配置里加一个「WebSocket 客户端」，填上下面的地址和令牌，消息格式选数组。",
    "guide/title": "先做这三步",
    "guide/token": "生成令牌：按下面「访问令牌」那一行的「生成」。",
    "guide/wait": "等几秒，下面 NapCat 那一行变成「已连上」。",
    "loading": "正在连接入QQ…",
    "napcat": "NapCat",
    "napcat/bot": "机器人 {bot}",
    "napcat/connected": "已连上",
    "napcat/detail": "{implementation} {version} · 机器人 {bot}",
    "napcat/disconnected": "没连上",
    "napcat/unknown": "看不到桥的状态：{reason}",
    "nav/connection": "连接",
    "nav/whitelist": "白名单成员",
    "ports/listen": "NapCat 连进来",
    "ports/listen-in-use": "端口 {port} 被占了，桥照旧用原来的端口。换一个再保存。",
    "ports/listen-moved": "NapCat 的端口换成了 {port}：NapCat 那边的地址也要跟着改成上面那一个。",
    "ports/title": "端口",
    "retry": "重试",
    "save": "保存",
    "saved": "存好了",
    "token/change": "换一个",
    "token/confirm": "换了以后，NapCat 那边也要跟着换成新令牌。换吗？",
    "token/env": "照环境变量 {name}",
    "token/generate": "生成",
    "token/hide": "收起",
    "token/set": "已设",
    "token/show": "显示",
    "token/unset": "没设",
    "whitelist/add": "加一个",
    "whitelist/admins": "终端管理员（这台机器的账号对应的 QQ 号）在网页的「高级」页里改，这里只管白名单成员。",
    "whitelist/bad-number": "号只能是数字，不以 0 开头",
    "whitelist/duplicate": "这个号重复了",
    "whitelist/empty": "还没有白名单成员。",
    "whitelist/hint": "能私聊 AI，加 AI 好友自动通过，不限流，睡觉时间里照样放行，群里冲 AI 来的直接回。",
    "whitelist/number": "QQ 号",
    "whitelist/remove": "删",
    "whitelist/title": "白名单成员"
  },
  "en": {
    "cancel": "Cancel",
    "copied": "Copied",
    "copy": "Copy",
    "failed": "Failed: {reason}",
    "fill/address": "Reverse WebSocket URL",
    "fill/array": "Array",
    "fill/format": "Message format",
    "fill/title": "What to enter in NapCat",
    "fill/token": "Access token",
    "fill/url": "ws://127.0.0.1:{port}{path}",
    "guide/napcat": "In NapCat's network settings, add a WebSocket client with the URL and token below, and choose Array as the message format.",
    "guide/title": "Three steps to connect",
    "guide/token": "Generate a token: press Generate in the Access token row below.",
    "guide/wait": "Wait a few seconds until NapCat below shows Connected.",
    "loading": "Connecting to Connect QQ…",
    "napcat": "NapCat",
    "napcat/bot": "bot {bot}",
    "napcat/connected": "Connected",
    "napcat/detail": "{implementation} {version} · bot {bot}",
    "napcat/disconnected": "Not connected",
    "napcat/unknown": "Bridge status unavailable: {reason}",
    "nav/connection": "Connection",
    "nav/whitelist": "Whitelist",
    "ports/listen": "NapCat connects to",
    "ports/listen-in-use": "Port {port} is in use, so the bridge keeps its old port. Pick another one and save again.",
    "ports/listen-moved": "NapCat's port is now {port}: change the URL in NapCat to the one above.",
    "ports/title": "Ports",
    "retry": "Retry",
    "save": "Save",
    "saved": "Saved",
    "token/change": "New token",
    "token/confirm": "NapCat will need the new token as well. Change it?",
    "token/env": "From the environment variable {name}",
    "token/generate": "Generate",
    "token/hide": "Hide",
    "token/set": "Set",
    "token/show": "Show",
    "token/unset": "Not set",
    "whitelist/add": "Add",
    "whitelist/admins": "Terminal admins (QQ numbers that are a local account here) are set on the Advanced page of the web UI; this page only manages the whitelist.",
    "whitelist/bad-number": "Digits only, not starting with 0",
    "whitelist/duplicate": "This number is listed twice",
    "whitelist/empty": "No one on the whitelist yet.",
    "whitelist/hint": "They can chat with the AI in private, their friend requests are accepted, no rate limit, even while the AI sleeps; in groups the AI answers them directly.",
    "whitelist/number": "QQ number",
    "whitelist/remove": "Remove",
    "whitelist/title": "Whitelist"
  },
  "ja": {
    "cancel": "Cancel",
    "copied": "Copied",
    "copy": "Copy",
    "failed": "Failed: {reason}",
    "fill/address": "Reverse WebSocket URL",
    "fill/array": "Array",
    "fill/format": "Message format",
    "fill/title": "What to enter in NapCat",
    "fill/token": "Access token",
    "fill/url": "ws://127.0.0.1:{port}{path}",
    "guide/napcat": "In NapCat's network settings, add a WebSocket client with the URL and token below, and choose Array as the message format.",
    "guide/title": "Three steps to connect",
    "guide/token": "Generate a token: press Generate in the Access token row below.",
    "guide/wait": "Wait a few seconds until NapCat below shows Connected.",
    "loading": "Connecting to Connect QQ…",
    "napcat": "NapCat",
    "napcat/bot": "bot {bot}",
    "napcat/connected": "Connected",
    "napcat/detail": "{implementation} {version} · bot {bot}",
    "napcat/disconnected": "Not connected",
    "napcat/unknown": "Bridge status unavailable: {reason}",
    "nav/connection": "Connection",
    "nav/whitelist": "Whitelist",
    "ports/listen": "NapCat connects to",
    "ports/listen-in-use": "Port {port} is in use, so the bridge keeps its old port. Pick another one and save again.",
    "ports/listen-moved": "NapCat's port is now {port}: change the URL in NapCat to the one above.",
    "ports/title": "Ports",
    "retry": "Retry",
    "save": "Save",
    "saved": "Saved",
    "token/change": "New token",
    "token/confirm": "NapCat will need the new token as well. Change it?",
    "token/env": "From the environment variable {name}",
    "token/generate": "Generate",
    "token/hide": "Hide",
    "token/set": "Set",
    "token/show": "Show",
    "token/unset": "Not set",
    "whitelist/add": "Add",
    "whitelist/admins": "Terminal admins (QQ numbers that are a local account here) are set on the Advanced page of the web UI; this page only manages the whitelist.",
    "whitelist/bad-number": "Digits only, not starting with 0",
    "whitelist/duplicate": "This number is listed twice",
    "whitelist/empty": "No one on the whitelist yet.",
    "whitelist/hint": "They can chat with the AI in private, their friend requests are accepted, no rate limit, even while the AI sleeps; in groups the AI answers them directly.",
    "whitelist/number": "QQ number",
    "whitelist/remove": "Remove",
    "whitelist/title": "Whitelist"
  }
};
